version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:5000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next

networks:
  app-network:
    driver: bridge
