version: "3.8"

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
